apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vas-aggregator-subscription-billing
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      com.terragonbase.service: vas-aggregator-subscription-billing