apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: vas-aggregator-subscription-billing
    labels:
      com.terragonbase.service: vas-aggregator-subscription-billing
spec:
    replicas: 1
    strategy: Recreate
    revisionHistoryLimit: 10
    selector:
      matchLabels:
          com.terragonbase.service: vas-aggregator-subscription-billing
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
      type: RollingUpdate
    template:
          metadata:
            labels:
              com.terragonbase.service: vas-aggregator-subscription-billing
          spec:
            imagePullSecrets:
                  - name: aggregator-acr-key                
            containers:
                  - name: vas-aggregator-subscription-billing
                    env:
                      - name: PORT
                        value: '3337'
                      - name: NINE_MOBILE_AGGREGATOR_BASEURL
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_BASEURL
                      - name: NINE_MOBILE_SUBSCRIPTION_KEY
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_SUBSCRIPTION_KEY
                      - name: APP_NAME
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: APP_NAME
                      - name: NINE_MOBILE_AGGREGATOR_ID
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_ID
                      - name: NINE_MOBILE_SUBSCRIPTION_KEY
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_SUBSCRIPTION_KEY
                      - name: NINE_MOBILE_AGGREGATOR_USERNAME
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_USERNAME
                      - name: NINE_MOBILE_AGGREGATOR_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_PASSWORD
                      - name: MONGODB_DATABASE_NAME
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: MONGODB_DATABASE_NAME
                      - name: MONGODB_PORT
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: MONGODB_PORT
                      - name: MONGODB_HOST
                        valueFrom:
                          secretKeyRef: 
                            name: vas-aggregator-subscription-billing-secrets
                            key:  MONGODB_HOST
                      - name: MONGODB_PASSWORD
                        valueFrom:
                          secretKeyRef: 
                            name: vas-aggregator-subscription-billing-secrets
                            key:  MONGODB_PASSWORD
                      - name: MONGODB_USER
                        valueFrom:
                          secretKeyRef: 
                            name: vas-aggregator-subscription-billing-secrets
                            key:  MONGODB_USER
                      - name: REDIS_PORT
                        valueFrom:
                          configMapKeyRef:
                            name: vas-aggregator-secrets
                            key: REDIS_PORT
                      - name: REDIS_HOST
                        valueFrom:
                          configMapKeyRef:
                            name: vas-aggregator-secrets
                            key: REDIS_HOST
                      - name: REDIS_PASSWORD
                        valueFrom:
                          configMapKeyRef:
                            name: vas-aggregator-secrets
                            key: REDIS_PASSWORD
                      - name: AIRTEL_SE_LOG_QUEUE_NAME
                        valueFrom:
                          secretKeyRef: 
                            name: vas-aggregator-subscription-billing-secrets
                            key:  AIRTEL_SE_LOG_QUEUE_NAME
                      - name: RABBITMQ_HOST
                        valueFrom:
                          configMapKeyRef:
                              name: vas-aggregator-secrets
                              key: RABBITMQ_HOST
                      - name: RABBITMQ_PORT
                        valueFrom:
                          configMapKeyRef:
                              name: vas-aggregator-secrets
                              key: RABBITMQ_PORT
                      - name: RABBITMQ_USER
                        valueFrom:
                          configMapKeyRef:
                              name: vas-aggregator-secrets
                              key: RABBITMQ_USER
                      - name: RABBITMQ_PORT
                        valueFrom:
                          configMapKeyRef:
                              name: vas-aggregator-secrets
                              key: RABBITMQ_PORT
                      - name: RABBITMQ_HOST
                        valueFrom:
                          configMapKeyRef:
                              name: vas-aggregator-secrets
                              key: RABBITMQ_HOST
                      - name: RABBITMQ_VHOST
                        valueFrom:
                          configMapKeyRef:
                              name: vas-aggregator-secrets
                              key: RABBITMQ_VHOST
                      - name: AIRTEL_SE_AIRTEL_HOST
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_AIRTEL_HOST 
                      - name: AIRTEL_SE_AIRTEL_PORT
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_AIRTEL_PORT
                      - name: AIRTEL_SE_CLIENT_TIMEOUT
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_CLIENT_TIMEOUT
                      - name: AIRTEL_SE_CLIENT_WSDL_PATH
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_CLIENT_WSDL_PATH
                      - name: AIRTEL_SE_CLIENT_BLACKLIST_BASE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_CLIENT_BLACKLIST_BASE_URL
                      - name: MTN_SPID
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_SPID
                      - name: MTN_SPPWD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_SPPWD
                      - name: PARTNER_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: PARTNER_PASSWORD
                      - name: PARTNER_USERNAME
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: PARTNER_USERNAME
                      - name: REDIS_SECRET
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: REDIS_SECRET
                      - name: NOTIFICATION_SERVICE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: NOTIFICATION_SERVICE_URL 
                      - name: AIRTEL_SE_SUBSCRIPTION_BASE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_SUBSCRIPTION_BASE_URL
                      - name: PARTNER_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: PARTNER_PASSWORD
                      - name: PARTNER_USERNAME
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: PARTNER_USERNAME
                      - name: NINE_MOBILE_POSTBACK_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: NINE_MOBILE_POSTBACK_QUEUE
                      - name: NINE_MOBILE_UNSUBSCRIPTION_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: NINE_MOBILE_UNSUBSCRIPTION_QUEUE
                      - name: NINE_MOBILE_SUBSCRIPTION_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: NINE_MOBILE_SUBSCRIPTION_QUEUE
                      - name: AIRTEL_POSTBACK_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_POSTBACK_QUEUE
                      - name: AIRTEL_UNSUBSCRIPTION_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_UNSUBSCRIPTION_QUEUE
                      - name: AIRTEL_SUBSCRIPTION_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SUBSCRIPTION_QUEUE
                      - name: MTN_POSTBACK_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_POSTBACK_QUEUE
                      - name: MTN_UNSUBSCRIPTION_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_UNSUBSCRIPTION_QUEUE
                      - name: MTN_SUBSCRIPTION_QUEUE
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_SUBSCRIPTION_QUEUE
                      - name: AIRTEL_SE_CLIENT_WSDL_PATH
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_CLIENT_WSDL_PATH
                      - name: AIRTEL_CP_ID
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_CP_ID
                      - name: AIRTEL_CP_NAME
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_CP_NAME
                      - name: AIRTEL_CP_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_CP_PASSWORD                                  
                    image: 101063123548.dkr.ecr.eu-west-1.amazonaws.com/vas-aggregator-subscription-billing/vas-aggregator-subscription-billing:latest
                    ports:
                      - containerPort: 3337
                        name: tcp3000
                        protocol: TCP
                    imagePullPolicy: Always
