apiVersion: apps/v1
kind: Deployment
metadata:
    name: vas-aggregator-subscription-billing
    labels:
      com.terragonbase.service: vas-aggregator-subscription-billing
spec:
    replicas: 1
    strategy: Recreate
    revisionHistoryLimit: 10
    selector:
      matchLabels:
          com.terragonbase.service: vas-aggregator-subscription-billing
    strategy:
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1
      type: RollingUpdate
    template:
          metadata:
            labels:
              com.terragonbase.service: vas-aggregator-subscription-billing
          spec:
            imagePullSecrets:
                  - name: aggregator-acr-key                
            containers:
                  - name: vas-aggregator-subscription-billing
                    env:
                      - name: PORT
                        value: '3337'
                      - name: NINE_MOBILE_AGGREGATOR_BASEURL
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_BASEURL
                      - name: APP_BASE_URL
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: APP_BASE_URL
                      - name: INTERNAL_SECURITY_TOKEN
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: INTERNAL_SECURITY_TOKEN
                      - name: APP_NAME
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: APP_NAME
                      - name: NINE_MOBILE_SUBSCRIPTION_KEY
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_SUBSCRIPTION_KEY
                      - name: NINE_MOBILE_AGGREGATOR_USERNAME
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_USERNAME
                      - name: NINE_MOBILE_AGGREGATOR_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_PASSWORD
                      - name: NINE_MOBILE_AGGREGATOR_ID
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: NINE_MOBILE_AGGREGATOR_ID
                      - name: MONGODB_DATABASE_NAME
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: MONGODB_DATABASE_NAME
                      - name: MONGODB_PORT
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: MONGODB_PORT
                      - name: MONGODB_HOST
                        valueFrom:
                          secretKeyRef: 
                            name: vas-aggregator-subscription-billing-secrets
                            key:  MONGODB_HOST
                      - name: MONGODB_PASSWORD
                        valueFrom:
                          secretKeyRef: 
                            name: vas-aggregator-subscription-billing-secrets
                            key:  MONGODB_PASSWORD
                      - name: MONGODB_USER
                        valueFrom:
                          secretKeyRef: 
                            name: vas-aggregator-subscription-billing-secrets
                            key:  MONGODB_USER
                      - name: REDIS_PORT
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: REDIS_PORT
                      - name: REDIS_HOST
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: REDIS_HOST
                      - name: REDIS_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: REDIS_PASSWORD
                      - name: RABBITMQ_HOST
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: RABBITMQ_HOST
                      - name: RABBITMQ_PORT
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: RABBITMQ_PORT
                      - name: RABBITMQ_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: RABBITMQ_PASSWORD
                      - name: RABBITMQ_USER
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: RABBITMQ_USER
                      - name: RABBITMQ_VHOST
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: RABBITMQ_VHOST
                      - name: AIRTEL_SE_AIRTEL_HOST
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_AIRTEL_HOST
                      - name: SUB_SERVICE_URL
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: SUB_SERVICE_URL
                      - name: MOCK_APP_URL
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: MOCK_APP_URL
                      - name: AUTHORIZE_PAYMENT_FEEDBACK_URL
                        valueFrom:
                          secretKeyRef:
                            name: vas-aggregator-subscription-billing-secrets
                            key: AUTHORIZE_PAYMENT_FEEDBACK_URL
                      - name: AIRTEL_SE_AIRTEL_PORT
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_AIRTEL_PORT
                      - name: WSDL_PATH
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: WSDL_PATH
                      - name: MTN_SPID
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_SPID
                      - name: MTN_SPPWD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_SPPWD
                      - name: REDIS_SECRET
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: REDIS_SECRET
                      - name: NOTIFICATION_SERVICE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: NOTIFICATION_SERVICE_URL
                      - name: SUBSCRIPTION_SERVICE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: SUBSCRIPTION_SERVICE_URL
                      - name: SMS_USSD_IVR_ONBOARDING_SERVICE_URL 
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: SMS_USSD_IVR_ONBOARDING_SERVICE_URL 
                      - name: AIRTEL_SE_SUBSCRIPTION_BASE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_SE_SUBSCRIPTION_BASE_URL
                      - name: PARTNER_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: PARTNER_PASSWORD
                      - name: PARTNER_USERNAME
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: PARTNER_USERNAME
                      - name: AIRTEL_CP_ID
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_CP_ID
                      - name: AIRTEL_CP_NAME
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_CP_NAME
                      - name: AIRTEL_CP_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: AIRTEL_CP_PASSWORD
                      - name: MTN_SDP_MODULE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_SDP_MODULE_URL
                      - name: SMS_NOTIFICATION_STATUS_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: SMS_NOTIFICATION_STATUS_URL
                      - name: ON_DEMAND_SERVICE_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: ON_DEMAND_SERVICE_URL
                      - name: NOTIFICATION_SERVICE_ENDPOINT
                        valueFrom:
                          configMapKeyRef:
                            name: vas-services-configs
                            key: NOTIFICATION_SERVICE_ENDPOINT
                      - name: MTN_MADAPI_CLIENT_ID
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_MADAPI_CLIENT_ID
                      - name: MTN_MADAPI_CLIENT_SECRET
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_MADAPI_CLIENT_SECRET
                      - name: MTN_MADAPI_BAS_URL
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_MADAPI_BAS_URL                               
                      - name: MTN_MADAPI_X_API_KEY
                        valueFrom:
                          secretKeyRef:
                              name: vas-aggregator-subscription-billing-secrets
                              key: MTN_MADAPI_X_API_KEY                               
                    image: 101063123548.dkr.ecr.eu-west-1.amazonaws.com/vas-aggregator-subscription-billing/vas-aggregator-subscription-billing:latest
                    ports:
                      - containerPort: 3337
                        name: tcp3000
                        protocol: TCP
                    imagePullPolicy: Always
